name = "RootIO"
uuid = "84287b9e-b673-4340-bb1d-a334fb11fbd4"
authors = ["Yash Solanki <67216443+yashnator@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
ROOT = "1706fdcc-8426-44f1-a283-5be479e9517c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
